name: Deploy

# When will this workflow trigger?
on:
  push:
    branches: [main]

# What's going to happen whenever it's triggered?
jobs:
  test:
    name: Test Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 16.x
      - run: npm ci
      - run: npm test

  # unique id for this job:
  build_and_deploy:
    name: Build and Deploy
    # needs: could go here if depends on another job; leave off if not needed
    needs: test
    # runs-on what system?  Docker :
    runs-on: ubuntu-latest
    # steps?
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # These steps install and run Railway through GitHub
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}